//! Ubuntu's user-namespace restriction, and the AppArmor profile that lifts it
//! for sarab-ns alone. Since Ubuntu 23.10 `kernel.apparmor_restrict_unprivileged_userns`
//! is 1 (`restricted`): a program no AppArmor profile allows `userns` either
//! cannot create a user namespace, or gets one while being moved into the
//! `unprivileged_userns` profile, which denies every capability in it. sarab-ns
//! then fails at its first privileged step, and setup at its first extraction,
//! with a bare "Permission denied". sarab-ns checks both ways after its unshare
//! (`confined` reads its own label), and `sarab setup` checks before it
//! downloads anything; both say `blocked`, which ends in the one fix (`FIX`).
//!
//! `profile` is the profile that fix installs as `PROFILE_FILE`: it attaches to
//! sarab-ns's exact path, is `unconfined` apart from that (it restricts
//! nothing sarab-ns could do before), allows `userns`, and includes
//! `local/sarab-ns` for additions of the machine's own, which is where they
//! belong, since `sarab setup` compares the whole file with this text. The
//! path goes in quotes, so spaces are fine; a path with a character AppArmor
//! would read as a glob or as syntax (`SPECIAL`) is refused rather than
//! escaped. An allowed sarab-ns is as good as unrestricted user namespaces
//! for whoever can replace the file, so an install the user can write to
//! lifts the restriction for that user (SECURITY.md).

use std::path::Path;

pub const PROFILE_FILE: &str = "/etc/apparmor.d/sarab-ns";
pub const FIX: &str = "sarab apparmor-profile | sudo tee /etc/apparmor.d/sarab-ns >/dev/null && sudo apparmor_parser -r /etc/apparmor.d/sarab-ns";
const RESTRICT: &str = "/proc/sys/kernel/apparmor_restrict_unprivileged_userns";
const CONFINED: &str = "unprivileged_userns";
const LABELS: &[&str] = &["/proc/self/attr/apparmor/current", "/proc/self/attr/current"];
const SPECIAL: &[char] = &['"', '\\', '*', '?', '[', ']', '{', '}', '^', '#', '\n', '\0'];

pub fn restricted() -> bool {
    std::fs::read_to_string(RESTRICT).is_ok_and(|s| s.trim() == "1")
}

pub fn confined() -> bool {
    LABELS.iter().find_map(|f| std::fs::read_to_string(f).ok()).is_some_and(|l| l.starts_with(CONFINED))
}

pub fn blocked(reason: &str) -> String {
    format!(
        "{reason}. With kernel.apparmor_restrict_unprivileged_userns=1 (Ubuntu's default since 23.10) AppArmor \
         takes every capability from a user namespace an unlisted program creates, and Android runs in one. \
         Allow sarab-ns, once:\n  {FIX}"
    )
}

pub fn profile(ns: &Path) -> Result<String, String> {
    let path = ns.to_str().filter(|p| p.starts_with('/') && !p.contains(SPECIAL)).ok_or_else(|| {
        format!("{} cannot be named in an AppArmor profile as it is; install sarab under a plainer path", ns.display())
    })?;
    Ok(format!(
        "# Generated by `sarab apparmor-profile`: lets sarab-ns create the user namespace Android runs in.\n\
         # Additions of your own go in /etc/apparmor.d/local/sarab-ns.\n\
         abi <abi/4.0>,\n\
         include <tunables/global>\n\
         \n\
         profile sarab-ns \"{path}\" flags=(unconfined) {{\n  \
         userns,\n\
         \n  \
         include if exists <local/sarab-ns>\n\
         }}\n"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_profile_attaches_to_the_exact_path_and_allows_only_userns() {
        let p = profile(Path::new("/home/a b/.local/lib/sarab/sarab-ns")).unwrap();
        assert!(
            p.contains("profile sarab-ns \"/home/a b/.local/lib/sarab/sarab-ns\" flags=(unconfined) {\n  userns,\n")
        );
        assert!(p.starts_with("# Generated") && p.ends_with("}\n"));
        assert!(p.contains("abi <abi/4.0>,") && p.contains("include if exists <local/sarab-ns>"));
        for bad in ["relative/sarab-ns", "/opt/sarab*/sarab-ns", "/opt/{a,b}/sarab-ns", "/opt/\"q\"/sarab-ns"] {
            assert!(profile(Path::new(bad)).is_err(), "{bad}");
        }
    }

    #[test]
    fn the_message_ends_in_the_fix() {
        let m = blocked("no profile allows sarab-ns");
        assert!(m.starts_with("no profile allows sarab-ns. With kernel.apparmor_restrict_unprivileged_userns=1"));
        assert!(m.ends_with(&format!("\n  {FIX}")));
    }
}
